@startuml

class Bank
class Kid
class Parent

package core {
    class Account
    class Transaction
    class Credit
    class Debit
}

Debit --|> Transaction : is-a
Credit --|> Transaction : is-a

Bank *- Kid
Kid *- Account
Account <-- Transaction :  operates \non
Transaction <-right- Parent : makes

@enduml