package io.github.joaovicente.piggybank.mapper;

import io.github.joaovicente.piggybank.dto.KidDto;
import io.github.joaovicente.piggybank.entity.Kid;
import org.junit.Test;
import org.modelmapper.ModelMapper;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

public class KidMapperTest {
    private final ModelMapper modelMapper = new ModelMapper();
    final String NAME = "Albert";
    String ID = "51459636-51f8-4f90-ac17-2439b5a4de59";
    final int RANDOMLY_GENERATED_UUID = 4;

    @Test
    public void KidToKidDto() {
        Kid kid = Kid.builder()
                .name(NAME)
                .build();

        KidDto kidDto = modelMapper.map(kid, KidDto.class);
        assertThat(kidDto.getName()).isEqualTo(kid.getName());
        assertThat(kidDto.getId()).isEqualTo(kid.getId());
        assertThat(UUID.fromString(kidDto.getId()).version()).isEqualTo(RANDOMLY_GENERATED_UUID);
    }

    @Test
    public void KidDtoToKid() {
        KidDto kidDto = KidDto.builder()
                .name(NAME)
                .build();
        Kid kid = modelMapper.map(kidDto, Kid.class);
        assertThat(kid.getName()).isEqualTo(kidDto.getName());
        // kidId should always be generated by the model
        assertThat(UUID.fromString(kid.getId()).version()).isEqualTo(RANDOMLY_GENERATED_UUID);
    }
}
